[log]
level = "debug"
path = "./indexer.log"
pretty = true

#App configuration values
[base]
# start-block = 14907544   # start indexing at beginning of the blockchain, -1 to resume from highest block indexed
# end-block = 14938581   # stop indexing at this block, -1 to never stop indexing

# for debug 0xb7079cb88239bd68c021ef916785431430f861b6928a4b69ea586704783d6256-3
# start-block = 15032350
# start-block = 16300955 # for axelar-testnet-rpc.qubelabs
start-block = 1
end-block = -1

throttling = 0.5
block-timer = 10000 #print out how long it takes to process this many blocks
wait-for-chain = false #if true, indexer will start when the node is caught up to the blockchain
wait-for-chain-delay = 10 #seconds to wait between each check for node to catch up to the chain
index-transactions = true #If false, we won't attempt to index the chain
exit-when-caught-up = true #mainly used for Osmosis rewards indexing
index-block-events = true #index block events for the particular chain
dry = false # if true, indexing will occur but data will not be written to the database.
rpc-workers = 1
reindex = true
reattempt-failed-blocks = false

# Provides a filter configuration to skip block events or message types based on patterns
# filter-file="filter-config.json"

#Lens config options
[probe]
# rpc = "https://axelar-rpc.polkachu.com:443/"
# rpc = "https://axelar-testnet-rpc.qubelabs.io:443/"
# rpc = "https://axelar.drpc.org" # This is the official axelar chain, but it is not free
# rpc = "http://localhost:26657" # This is the local core
rpc = "http://node.testnet.scalar.org" # This is the testnet core node
account-prefix = "cosmos"
chain-id = "scalar-testnet-4"
chain-name = "ScalarXchains"

# Flags for extending or modifying the indexed dataset
[flags]
index-tx-message-raw=false
block-events-base64-encoded=true

[database]
host = "localhost"
port = "5452"
database = "xchains_indexer"
user = "postgres"
password = "postgres"
log-level = ""
